### ISSUE TITLE
Hello (again) SpiderNode

### ISSUE THREAD

**Issue by joshgav** [nodejs/vm#2]
Ehsan's [blog post](https://ehsanakhgari.org/blog/2016-04-20/project-spidernode) covers what you need to know, notably that he followed the same pattern as node-chakracore of shimming to V8 APIs.

Related repos:
[mozilla/spidernode](https://github.com/mozilla/spidernode)
[mozilla/positron](https://github.com/mozilla/positron)

/cc @ehsan @aruneshchandra @ofrobots

**Comment by jasnell** [comment]
Awesome! Great to see! If the spidernode team would like, we can easily create a team for them here like we have done with the @nodejs/v8 and @nodejs/chakracore teams and I can add them to this repo.

**Comment by mikeal** [comment]
yup, could even more the repo here if they prefer ;)

**Comment by ehsan** [comment]
> Awesome! Great to see! If the spidernode team would like, we can easily create a team for them here like we have done with the @nodejs/v8 and @nodejs/chakracore teams and I can add them to this repo.

Hello there!  Those two links are 404 for me, but sure, if you'd like to add me to a team, please do so!  So far SpiderNode has been a one man project.

**Comment by ehsan** [comment]
> yup, could even more the repo here if they prefer ;)

I'd be open to that, but perhaps we should do that once SpiderNode works.  So far there are about 135 V8 functions that I need to implement before we can even link the node executable!  I hope to get there in the next few weeks.

My ultimate goal is to upstream all of this work to the main node repo.  I'm still not sure what the process for that would look like, but I'd be happy to do whatever you guys suggest.  :)

**Comment by jasnell** [comment]
@ehsan ... the approach we've taken with chakra is to create a separate node-chakra repo that tracks master. If there are any changes that affect node in general (that aren't specific to chakra), those can be upstreamed into the main master, otherwise they go into the chakra repo. For the time being, that's likely the process we'd follow with this also. Once we get further down the road in terms of officially supporting multiple VMs (assuming we get there) we can look again at what gets merged where, but so far the separate repo approach seems to be working rather well.

It's excellent to see this work! I've created the @nodejs/spidernode team and added you to it. Let me know if there's anyone else who should be included in that.

**Comment by mikeal** [comment]
to reiterate what james is saying, as Node.js is supported on top of more VMs it's going to become more and more of a problem to checkin all of the VM code as we do now with V8. rather than block the work happening to support more VMs on resolving this issue (which is quite massive, it would require a lot of build system changes) the approach has been to use separate repos.

**Comment by ehsan** [comment]
> @ehsan ... the approach we've taken with chakra is to create a separate node-chakra repo that tracks master.

Yeah.  The SpiderNode repo is actually based on https://github.com/nodejs/node-chakracore, and I'm merging with the chakracore-master branch from that repo regularly.

> If there are any changes that affect node in general (that aren't specific to chakra), those can be upstreamed into the main master, otherwise they go into the chakra repo. For the time being, that's likely the process we'd follow with this also. Once we get further down the road in terms of officially supporting multiple VMs (assuming we get there) we can look again at what gets merged where, but so far the separate repo approach seems to be working rather well.

Makes sense.  This is how I assumed the process would work, so sounds like all is good!  So far I haven't made any modifications outside of spidershim except for a few build system changes to integrate with the SpiderMonkey backend.  I'll submit Node PRs if I need to modify Node.

> It's excellent to see this work! I've created the @nodejs/spidernode team and added you to it. Let me know if there's anyone else who should be included in that.

Cool, thanks a lot!  Will do.

**Comment by ehsan** [comment]
> to reiterate what james is saying, as Node.js is supported on top of more VMs it's going to become more and more of a problem to checkin all of the VM code as we do now with V8. rather than block the work happening to support more VMs on resolving this issue (which is quite massive, it would require a lot of build system changes) the approach has been to use separate repos.

Makes sense!

FWIW I'm trying to upstream any SpiderMonkey modifications needed to the Mozilla upstream repo so that we can build against a pristine SpiderMonkey library in the future.  So far there is only one patch applied on top of SpiderMonkey.  With this approach, we'll have the option of building SpiderMonkey from a normal Mozilla checkout (or whatever) and not have to carry out a full copy of SpiderMonkey in the Node repo when/if this ends up being merged to the Node upstream.

**Comment by joshgav** [comment]
@ehsan we'd love your thoughts on the work in https://github.com/nodejs/abi-stable-node and the related PR at [node#11975](https://github.com/nodejs/node/pull/11975).

In the meantime I'll close this issue.
